services:
  - type: web
    name: amberalert
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate --noinput
    startCommand: gunicorn amber_alert_project.wsgi:application
