# Generated by Django 5.2.3 on 2025-06-18 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertaamber',
            name='activa',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='alertaamber',
            name='fecha_desaparicion',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='alertaamber',
            name='numero_reporte',
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
    ]
